### ISSUE TITLE
Error if no openvex output

### ISSUE THREAD

**Issue by R3DRUN3** [project-copacetic/copa-action#34]
## The Issue
The action raises an error in the event that *Trivy* does not find fixable vulnerabilities and *Copa* does not generate the Openvex output.

## How to Reproduce

Test the `patch` action with the image `docker.io/library/python:3.11.7-slim-bookworm`, in this case the Copa Action fails with the following error:  

```console
chmod: cannot access './data/docker.io-library-python-3.11.7-slim-bookworm-openvex-report.json': No such file or directory
Error: Process completed with exit code 1.
```

**Comment by sozercan** [comment]
related #499 to handle this on copa level too
